"""add user_id to provider_configs

Revision ID: b8d659f2754b
Revises: c3a2d8f9b741
Create Date: 2026-08-11 18:55:14.492423

"""
from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'b8d659f2754b'
down_revision: str | Sequence[str] | None = 'c3a2d8f9b741'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('provider_configs', sa.Column('user_id', sa.Integer(), nullable=True))
    op.drop_constraint(op.f('uq_provider_configs_kind_provider'), 'provider_configs', type_='unique')
    op.create_index(op.f('ix_provider_configs_user_id'), 'provider_configs', ['user_id'], unique=False)
    op.create_index('uq_provider_configs_kind_provider_default', 'provider_configs', ['kind', 'provider'], unique=True, postgresql_where=sa.text('user_id IS NULL'))
    op.create_unique_constraint('uq_provider_configs_user_kind_provider', 'provider_configs', ['user_id', 'kind', 'provider'])
    op.create_foreign_key(
        'fk_provider_configs_user_id_users',
        'provider_configs', 'users', ['user_id'], ['id'], ondelete='CASCADE'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_provider_configs_user_id_users', 'provider_configs', type_='foreignkey')
    op.drop_constraint('uq_provider_configs_user_kind_provider', 'provider_configs', type_='unique')
    op.drop_index('uq_provider_configs_kind_provider_default', table_name='provider_configs', postgresql_where=sa.text('user_id IS NULL'))
    op.drop_index(op.f('ix_provider_configs_user_id'), table_name='provider_configs')
    op.create_unique_constraint(op.f('uq_provider_configs_kind_provider'), 'provider_configs', ['kind', 'provider'], postgresql_nulls_not_distinct=False)
    op.drop_column('provider_configs', 'user_id')
    # ### end Alembic commands ###
